import { model } from "mongoose";
import studentSchema from "./studentSchema.js";
import teacherSchema from "./teacherSchema.js";
import bookSchema from "./bookSchema.js";
import traineeSchema from "./traineeSchema.js";
import collegeSchema from "./collegeSchema.js";
import classRoomSchema from "./classRoomSchema.js";
import departmentSchema from "./departmentSchema.js";
import userSchema from "./userSchema.js";
import playerSchema from "./playerSchema.js";
import productSchema from "./productSchema.js";
import productReviewSchema from "./productReviewSchema.js";
import registerSchema from "./registerSchema.js";

export let Student = model("Student",studentSchema);
export let Teacher = model("Teacher",teacherSchema);
export let Book = model("Book", bookSchema);
export let Trainee = model("Trainee", traineeSchema);
export let College = model("College", collegeSchema);
export let ClassRoom = model("ClassRoom", classRoomSchema);
export let Department = model("Department", departmentSchema);
export let User = model("User", userSchema);
export let Player = model("Player", playerSchema);
export let Product = model("Product", productSchema);
export let ProductReview = model("ProductReview", productReviewSchema);
export let Register = model("Register", registerSchema);